import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import boardsRouter from "./boards.js";
import standardsRouter from "./standards.js";
import subjectsRouter from "./subjects.js";
import chaptersRouter from "./chapters.js";
import topicsRouter from "./topics.js";
import questionTypesRouter from "./questionTypes.js";
import questionsRouter from "./questions.js";
import aiProvidersRouter from "./aiProviders.js";
import generationRouter from "./generation.js";
import papersRouter from "./papers.js";
import analyticsRouter from "./analytics.js";
import translateRouter from "./translate.js";
import exportRouter from "./export.js";
import chatRouter from "./chat.js";
import publicRouter from "./public.js";
import { plansRouter } from "./plans.js";
import { paymentsRouter } from "./payments.js";
import { studentsRouter } from "./students.js";
import { usersRouter } from "./users.js";
import settingsRouter from "./settings.js";
import freeAiRouter from "./freeAi.js";
import browserRouter from "./browser.js";
import pdfExtractorRouter from "./pdfExtractor.js";
import subAdminRouter from "./subAdmin.js";
import approvalsRouter from "./approvals.js";
import activityLogsRouter from "./activityLogs.js";
import studentPortalRouter from "./studentPortal.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(studentPortalRouter);
router.use(subAdminRouter);
router.use(approvalsRouter);
router.use(activityLogsRouter);
router.use(boardsRouter);
router.use(standardsRouter);
router.use(subjectsRouter);
router.use(chaptersRouter);
router.use(topicsRouter);
router.use(questionTypesRouter);
router.use(questionsRouter);
router.use(aiProvidersRouter);
router.use(generationRouter);
router.use(papersRouter);
router.use(analyticsRouter);
router.use(translateRouter);
router.use(exportRouter);
router.use(chatRouter);
router.use(freeAiRouter);
router.use(browserRouter);
router.use(pdfExtractorRouter);
router.use(publicRouter);
router.use(plansRouter);
router.use(paymentsRouter);
router.use(studentsRouter);
router.use(usersRouter);
router.use(settingsRouter);

export default router;
